import streamlit as st
import pandas as pd

st.set_page_config(page_title="Generate Report")

st.title("4 — Generate Report")

# -------------------------
# Validate analysis results
# -------------------------
if "analysis_results" not in st.session_state:
    st.warning("No analysis results found. Please run Risk Analysis first.")
    st.stop()

df = st.session_state["analysis_results"].copy()

# -------------------------
# Display top high-risk patients
# -------------------------
st.subheader("Top high-risk patients")

if "risk_level" in df.columns:
    top = df[df["risk_level"] == "High"].sort_values("risk_score", ascending=False).head(50)
else:
    top = df.sort_values("risk_score", ascending=False).head(50)

st.dataframe(top)

# -------------------------
# Generate HTML report
# -------------------------
st.markdown("---")
st.subheader("Generate simple HTML report")

report_name = st.text_input("Report file name", value="patient_risk_report")

if st.button("Create Report"):
    html = [
        "<html><head><meta charset='utf-8'><title>Patient Risk Report</title></head><body>",
        "<h1>Patient Risk Report</h1>",
        "<p>Generated by Patient Risk Assessment System</p>",
        df.head(200).to_html(index=False),
        "</body></html>"
    ]

    html_bytes = "\n".join(html).encode("utf-8")

    st.success("Report generated — use the download button below.")

    st.download_button(
        "Download HTML report",
        data=html_bytes,
        file_name=f"{report_name}.html",
        mime="text/html"
    )

st.markdown("---")
st.info("This report is a basic HTML export. For production PDFs, consider WeasyPrint or ReportLab.")
